[package]
name = "server"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8"
dashmap = "5.4"
fpe = "0.6"
rand = "0.8"
shared = { path = "../shared" }
